# Generated by Django 4.1.5 on 2023-01-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0001_initial"),
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="result",
            name="indicatorI",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="survey.indicatori"
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="school_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.school"
            ),
        ),
    ]
