# Generated by Django 4.1.5 on 2023-01-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="location",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
