# Generated by Django 4.1.5 on 2023-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_description_alter_school_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='description',
        ),
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='is_national',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='language',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='max_year',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='types',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
