# Generated by Django 4.1.5 on 2023-05-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_school_description_remove_school_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_national',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
