# Generated by Django 4.1.5 on 2023-05-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_school_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
