# Generated by Django 4.1.5 on 2023-01-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(
                choices=[
                    ("S", "School Student"),
                    ("T", "Teacher"),
                    ("P", "Parent"),
                    ("U", "Graduate"),
                ],
                max_length=2,
            ),
        ),
    ]
