# Generated by Django 4.1.5 on 2023-05-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
