# Generated by Django 4.1.5 on 2023-01-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("S", "School Student"),
                    ("T", "Teacher"),
                    ("P", "Parent"),
                    ("U", "Graduate"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
