# Generated by Django 4.1.5 on 2023-01-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_alter_indicatorii_indicatori_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorii",
            name="IndicatorI",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.indicatori",
            ),
        ),
        migrations.AlterField(
            model_name="indicatoriii",
            name="IndicatorII",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.indicatorii",
            ),
        ),
    ]
