# Generated by Django 4.1.5 on 2023-01-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_position"),
        ("survey", "0004_alter_indicatorii_indicatori_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="survey", name="user_id",),
        migrations.AddField(
            model_name="survey",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="User",
            ),
        ),
    ]
