# Generated by Django 4.1.5 on 2023-01-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_alter_school_description_alter_school_location"),
        ("user", "0002_alter_user_position"),
        ("survey", "0005_remove_survey_user_id_survey_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="survey", name="school_id",),
        migrations.AddField(
            model_name="survey",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school",
                to="school.school",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="user.user",
            ),
        ),
    ]
