# Generated by Django 4.1.5 on 2023-05-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_remove_survey_school_id_survey_school_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='question_id',
            new_name='question',
        ),
    ]
