# Generated by Django 4.1.5 on 2023-05-15 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_survey_question_remove_survey_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
